[package]
name = "dumbo"
version = "0.0.1"
edition = "2021"

[dependencies]
chrono = "0.4.38"
gethostname = "0.5.0"
minreq = { version = "2.12.0", features = ["https"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
sys-info = "0.9.1"
toml = "0.8.19"
